### ISSUE TITLE
trouble building due to costura error

### ISSUE THREAD

**Issue by zersiax** [pinky39/grove#1]
Trying to build this project on vs 2015 results in:

 Costura: Failed to extract target assembly path from the BuildEngine. 
Please raise a bug here http://code.google.com/p/costura/issues/list with the below exception text.
The temporary work-around is to change the weaving task as follows 
<EmbedTask ... TargetPath="@(TargetPath)" />
Exception details: System.Exception: Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
   at BuildEnginePropertyExtractor.GetProjectInstance() in d:\Builds\Costura\Costura\BuildEnginePropertyExtractor.cs:line 36
   at BuildEnginePropertyExtractor.GetEnvironmentVariable(String key, Boolean throwIfNotFound) in d:\Builds\Costura\Costura\BuildEnginePropertyExtractor.cs:line 60
   at TargetPathFinder.Execute() in d:\Builds\Costura\Costura\TargetPathFinder.cs:line 28. Project: Grove

I'd like to pick up development for this one if you are agreeable, but I'll need to have my toolchain able to build it first. Any help you can provide?

**Comment by pinky39** [comment]
Costura is there only to merge the dlls into single executable. If you are ok with multiple assemblies then you can leave it out. You can even implement this yourself if you want or adjust the project to use the new version:

https://github.com/Fody/Costura
